name: compress-bluej-project-folders
run-name: Compressing BlueJ Project Folders for download
on:
  push:
    paths-ignore: 
    - 'zips/'
jobs: 
  compress-files: 
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: for i in */; do zip -r "${i%/}.zip" "$i" && mv "${i%/}.zip" zips/; done
      - run: cd zips
      - run: git add .
      - run: git commit -m "chore: updating zip files"
      - run: git push origin main
